#pragma once
#include <XLPP/XLPP.h>
#include "TestOutput.h"
#include <chrono>
#include <filesystem>
#include <string>

namespace xlpp_numbered_tests {
using PerfClock = std::chrono::steady_clock;
struct BenchmarkResult {
    std::string benchmark;
    std::size_t rows{};
    std::size_t columns{};
    std::size_t cells{};
    double seconds{};
    std::uintmax_t bytes{};
    double rowsPerSecond() const { return seconds > 0.0 ? static_cast<double>(rows) / seconds : 0.0; }
    double cellsPerSecond() const { return seconds > 0.0 ? static_cast<double>(cells) / seconds : 0.0; }
    double mibPerSecond() const { return seconds > 0.0 ? static_cast<double>(bytes) / 1048576.0 / seconds : 0.0; }
};
template<class Fn> double measure(Fn&& fn) {
    const auto begin=PerfClock::now(); fn(); return std::chrono::duration<double>(PerfClock::now()-begin).count();
}
inline void writeBenchmarkWorkbook(const std::string& fileName, const BenchmarkResult& r, double threshold, const std::string& thresholdMetric) {
    xlpp::Workbook report; auto& summary=report.addWorksheet("Benchmark");
    summary.append({std::string("Metric"),std::string("Value")});
    summary.append({std::string("Benchmark"),r.benchmark});
    summary.append({std::string("Rows"),static_cast<double>(r.rows)});
    summary.append({std::string("Columns"),static_cast<double>(r.columns)});
    summary.append({std::string("Cells"),static_cast<double>(r.cells)});
    summary.append({std::string("Seconds"),r.seconds});
    summary.append({std::string("Rows/second"),r.rowsPerSecond()});
    summary.append({std::string("Cells/second"),r.cellsPerSecond()});
    summary.append({std::string("File bytes"),static_cast<double>(r.bytes)});
    summary.append({std::string("MiB/second"),r.mibPerSecond()});
    summary.append({std::string("Threshold metric"),thresholdMetric});
    summary.append({std::string("Threshold"),threshold});
    const double actual=thresholdMetric=="rows_per_second"?r.rowsPerSecond():r.cellsPerSecond();
    summary.append({std::string("Status"),std::string(actual>=threshold?"PASS":"FAIL")});
    summary.cell("B6").setNumberFormat("0.000000");
    summary.cell("B7").setNumberFormat("#,##0"); summary.cell("B8").setNumberFormat("#,##0"); summary.cell("B10").setNumberFormat("0.00");
    auto& environment=report.addWorksheet("Environment");
    environment.append({std::string("Property"),std::string("Value")});
    environment.append({std::string("Build"),std::string("Release recommended")});
    environment.append({std::string("Output file"),fileName});
    environment.append({std::string("Generated by"),std::string("XLPP numbered performance tests")});
    report.save(outputPath(fileName));
}
}
