#include <XLPP/XLPP.h>
#include "TestOutput.h"
#include <iostream>

void testWritePageSetup() {
    xlpp::Workbook workbook;
    auto& sheet = workbook.addWorksheet("Page Setup");
    sheet.append({std::string("ID"), std::string("Description"), std::string("Quantity"), std::string("Amount")});
    for (int row = 1; row <= 38; ++row)
        sheet.append({static_cast<double>(row), std::string("Printed row ") + std::to_string(row), static_cast<double>(row % 5 + 1), row * 12.5});
    sheet.columnDimension("A").width = 10.0;
    sheet.columnDimension("B").width = 28.0;
    sheet.columnDimension("C").width = 12.0;
    sheet.columnDimension("D").width = 14.0;

    sheet.pageSetup().setOrientation(xlpp::PageOrientation::Landscape);
    sheet.pageSetup().setPaperSize(xlpp::PaperSize::A4);
    sheet.pageSetup().setFitToPage(true);
    sheet.pageSetup().setFitToWidth(1);
    sheet.pageSetup().setFitToHeight(0);
    sheet.pageMargins().setLeft(0.4);
    sheet.pageMargins().setRight(0.4);
    sheet.pageMargins().setTop(0.6);
    sheet.pageMargins().setBottom(0.6);
    sheet.printOptions().setGridLines(true);
    sheet.printOptions().setHorizontalCentered(true);
    sheet.headerFooter().setOddHeader("&C&\"Calibri,Bold\"XL++ Page Setup Example");
    sheet.headerFooter().setOddFooter("&LGenerated by XL++&RPage &P of &N");
    sheet.setPrintArea("A1:D39");
    sheet.setPrintTitlesRows("1:1");
    workbook.save(xlpp_numbered_tests::outputPath("17_page_setup.xlsx"));
    std::cout << "Saved: 17_page_setup.xlsx\n";
}
