#include "RegressionTests.h"

void registerRegressionTests(std::vector<TestCase>& tests) {
    tests.push_back({"Formula Engine 2.0 dirty recalculation", testFormulaDirtyRecalculation});
    tests.push_back({"Advanced AutoFilter round-trip", testAdvancedAutoFilterRoundTrip});
    tests.push_back({"External data and Data Model inspection", testExternalDataAndDataModelInspection});
    tests.push_back({"Validation and conditional package regression", testValidationAndConditionalPackageRegression});
    tests.push_back({"Comment mutation after cached save", testCommentMutationAfterSave});
    tests.push_back({"Rich-text legacy comment import", testRichTextCommentImport});
    tests.push_back({"Print area, titles and fit-to-page", testPrintAreaTitlesAndFitToPage});
    tests.push_back({"Comprehensive formatting round-trip", testComprehensiveFormattingRoundTrip});
    tests.push_back({"Protection password add/remove", testProtectionPasswordAddRemove});
    tests.push_back({"Image package regression", testImagePackageRegression});
    tests.push_back({"Streaming pull iterator and shared strings", testStreamingSharedStringsAndPullIterator});
    tests.push_back({"Streaming read/write and benchmark", testStreamingReadWrite});
    tests.push_back({"Fast XML scanner", testXmlScanner});
    tests.push_back({"Fast XML scanner benchmark", testXmlScannerBenchmark});
    tests.push_back({"Date/time core", testDateTimeCore});
    tests.push_back({"Date cells XLSX round-trip", testDateCellsRoundTrip});
    tests.push_back({"Streaming shared-string writer", testSharedStringWriter});
    tests.push_back({"Parallel package pipeline", testParallelPackagePipeline});
    tests.push_back({"ZIP64, limits, cancel and progress", testZip64LimitsCancelProgress});
    tests.push_back({"ZIP64 forced write path", testZip64WritePath});
    tests.push_back({"Package part preservation", testPartPreservation});
    tests.push_back({"Binary package part preservation", testBinaryPartPreservation});
    tests.push_back({"VBA project package lifecycle", testVbaProjectPackageLifecycle});
    tests.push_back({"Chart part preservation", testChartPartPreservation});
    tests.push_back({"Relationship graph round-trip preservation", testRelationshipGraphRoundTripPreservation});
    tests.push_back({"Independent image/chart fixture round-trip", testIndependentImageChartFixtureRoundTrip});
    tests.push_back({"Drawing image reader metadata", testDrawingImageReaderMetadata});
    tests.push_back({"Absolute image anchor reader", testAbsoluteImageAnchorReader});
    tests.push_back({"Append image to preserved drawing", testAppendImageToPreservedDrawing});
    tests.push_back({"Selective imported image move and resize", testSelectiveImportedImageMoveResize});
    tests.push_back({"Selective absolute image move and resize", testSelectiveAbsoluteImageMoveResize});
    tests.push_back({"Selective imported image remove", testSelectiveImportedImageRemove});
    tests.push_back({"Selective image replace with shared media", testSelectiveImageReplaceWithSharedMedia});
    tests.push_back({"Multi-drawing selective mutation", testMultiDrawingSelectiveMutation});
    tests.push_back({"Unknown drawing relationship validation", testUnknownDrawingRelationshipValidation});
    tests.push_back({"Independent pivot fixture round-trip", testIndependentPivotFixtureRoundTrip});
    tests.push_back({"Imported pivot semantic edit", testImportedPivotSemanticEdit});
    tests.push_back({"Pivot semantic options round-trip", testPivotSemanticOptionsRoundTrip});
    tests.push_back({"Preserved and generated pivot coexistence", testPreservedAndGeneratedPivotCoexistence});
    tests.push_back({"Owner-reference and object regression detection", testOwnerReferenceAndObjectRegressionDetection});
    tests.push_back({"Extended owner graph and relationship hardening", testExtendedOwnerGraphAndRelationshipHardening});
    tests.push_back({"Package validator failure detection", testPackageValidatorFailureDetection});
    tests.push_back({"ZIP unique entry policy", testZipUniqueEntryPolicy});
    tests.push_back({"Pivot validation", testPivotValidation});
    tests.push_back({"Complete pivot generation round-trip", testCompletePivotGenerationRoundTrip});
    tests.push_back({"Pivot model validation and aggregation", testPivotModelValidationAndAggregation});
    tests.push_back({"Strict/transitional namespaces", testStrictNamespaces});
    tests.push_back({"Lenient load recovery", testLenientLoad});
    tests.push_back({"Malformed input hardening", testMalformedInputHardening});
    tests.push_back({"Core safety, atomic I/O and validation", testCoreSafetyAndValidation});
    tests.push_back({"Mutation fuzz", testMutationFuzz});
    tests.push_back({"Cell reference matrix", testCellReferenceMatrix});
    tests.push_back({"Cell error matrix", testCellErrorMatrix});
    tests.push_back({"xlfn() helper", testXlfnHelper});
    tests.push_back({"Formula metadata defaults", testFormulaMetadataDefaults});
    tests.push_back({"Number format detection", testNumberFormatDetection});
    tests.push_back({"Date/time boundaries", testDateTimeBoundaries});
    tests.push_back({"Streaming writer shared-string modes", testStreamingWriterModes});
    tests.push_back({"Streaming reader features", testStreamingReaderFeatures});
    tests.push_back({"Compression levels and parallel output", testCompressionLevelsAndParallel});
    tests.push_back({"Chart and pivot package", testChartAndPivotPackage});
    tests.push_back({"Pivot auto-cache from source", testPivotAutoCacheFromSource});
    tests.push_back({"Excel-compatible pivot view", testExcelCompatiblePivotView});
    tests.push_back({"Multiple pivot cache IDs", testMultiplePivotCacheIds});
    tests.push_back({"Strict pivot namespaces", testStrictPivotNamespaces});
    tests.push_back({"Imported chart selective mutation", testImportedChartInspectionAndSelectiveMutation});
    tests.push_back({"Imported scatter chart deep selective editing", testImportedScatterChartDeepSelectiveEditing});
    tests.push_back({"Imported combined chart axis structure", testImportedCombinedChartAxisStructure});
    tests.push_back({"Imported chart labels, trendlines and error bars", testImportedChartLabelsTrendlinesAndErrorBars});
    tests.push_back({"Imported chart per-point labels, custom error bars and formatting", testImportedChartPerPointCustomErrorsAndFormatting});
    tests.push_back({"Imported chart data-point, rich text and advanced formatting", testImportedChartDataPointRichTextAndAdvancedFormatting});
    tests.push_back({"Imported chart layout, axis and legend formatting", testImportedChartLayoutAxisLegendFormatting});
    tests.push_back({"Imported chart axis scaling, display units and area formatting", testImportedChartAxisScalingDisplayUnitsAndAreaFormatting});
    tests.push_back({"Imported chart auxiliary objects", testImportedChartAuxiliaryObjects});
    tests.push_back({"Stock chart structure, generation and data-table text", testStockChartStructureGenerationAndDataTableText});
    tests.push_back({"3D and surface chart preservation foundation", testThreeDSurfaceChartPreservationFoundation});
    tests.push_back({"Projected pie, doughnut and radar expansion", testProjectedPieDoughnutRadarExpansion});
    tests.push_back({"Chart style, theme and series caches", testChartStyleThemeAndSeriesCaches});
    tests.push_back({"Chart cache synchronization and theme transforms", testChartCacheSynchronizationAndThemeTransforms});
    tests.push_back({"Chart cache dependency tracking and auto save", testChartCacheDependencyTrackingAndAutoSave});
    tests.push_back({"Imported chart remove and append", testImportedChartRemoveAndAppend});
    tests.push_back({"Chart type names", testChartTypeNameMap});
    tests.push_back({"Excel chart family generation", testExcelChartFamilyGeneration});
    tests.push_back({"Internal hyperlink and memory stream", testInternalHyperlinkAndMemoryStream});
    tests.push_back({"Workbook edge cases", testWorkbookEdgeCases});
    tests.push_back({"Custom properties and calc round-trip", testCustomPropertiesAndCalcRoundTrip});
    tests.push_back({"Differential save cache", testDifferentialSaveCache});
    tests.push_back({"Strict after transitional save", testStrictAfterTransitionalSave});
    tests.push_back({"copyWorksheet aliasing", testCopyWorksheetAliasing});
    tests.push_back({"Reference stability across inserts", testReferenceStabilityAcrossInserts});
    tests.push_back({"Reference lifetime contract", testReferenceLifetimeContract});
    tests.push_back({"Workbook copy/move semantics", testWorkbookCopyMoveSemantics});
    tests.push_back({"Styled empty cells round-trip", testStyledEmptyCellsRoundTrip});
    tests.push_back({"Defined names full round-trip", testDefinedNamesFullRoundTrip});
    tests.push_back({"Row values and cells", testRowValuesAndCells});
    tests.push_back({"Date cell number format", testDateCellNumberFormat});
    tests.push_back({"CellRange operations", testCellRangeOperations});
    tests.push_back({"Properties full round-trip", testPropertiesFullRoundTrip});
    tests.push_back({"Hyperlink display and tooltip", testHyperlinkDisplayTooltipRoundTrip});
    tests.push_back({"Column dimension by name", testColumnDimensionByName});
    tests.push_back({"Advanced conditional formatting round-trip", testAdvancedConditionalFormattingRoundTrip});
    tests.push_back({"Advanced sheet view round-trip", testAdvancedSheetViewRoundTrip});
    tests.push_back({"AutoFilter mutation and operator matrix", testAutoFilterMutationAndOperatorMatrix});
    tests.push_back({"Cell overloads and optional models", testCellOverloadsAndOptionalModels});
    tests.push_back({"Table mutation round-trip", testTableMutationRoundTrip});
    tests.push_back({"Advanced page setup round-trip", testAdvancedPageSetupRoundTrip});
    tests.push_back({"Image file API", testImageFileApi});
    tests.push_back({"Workbook clear, const and VBA file API", testWorkbookClearConstAndVbaFileApi});
    tests.push_back({"Chart and pivot advanced model", testChartAndPivotAdvancedModel});
    tests.push_back({"Streaming accessors and post-increment", testStreamingAccessorsAndPostIncrement});
    tests.push_back({"Stored reference mutation after save", testStoredReferenceMutationAfterSave});
    tests.push_back({"Range bounds and indexed cell", testRangeBoundsAndIndexedCell});
    tests.push_back({"Remaining public mutation APIs", testRemainingPublicMutationApis});
    tests.push_back({"Internal IO and scanner coverage", testInternalIoAndScannerCoverage});
    tests.push_back({"VBA source text build and read", testVbaSourceTextBuildAndRead});
    tests.push_back({"External OOXML cell and style reader fixture", testExternalCellAndStyleReaderFixture});
    tests.push_back({"External OOXML worksheet feature reader fixture", testExternalWorksheetFeatureReaderFixture});
    tests.push_back({"External OOXML workbook metadata reader fixture", testExternalWorkbookMetadataReaderFixture});
}
