#!/usr/bin/env python3
"""Independent P1T interoperability gate using openpyxl.

Usage:
  python p1t_openpyxl_host_check.py <chartsheet.xlsx> <pivot.xlsx> [preserved_chartsheet.xlsx]

The files are generated by XLPP_P1T_ThreePillarTests when
XLPP_KEEP_P1T_ARTIFACTS=1 is set.
"""
from __future__ import annotations

import sys
from pathlib import Path
from openpyxl import load_workbook


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def check_chartsheet(path: Path) -> None:
    wb = load_workbook(path, data_only=False)
    require(wb.sheetnames == ["Data", "Chart View", "Notes"], "mixed workbook tab order")
    require([ws.title for ws in wb.worksheets] == ["Data", "Notes"], "worksheet-only view")
    require([cs.title for cs in wb.chartsheets] == ["Chart View"], "chartsheet discovery")
    cs = wb.chartsheets[0]
    require(len(cs._charts) == 1, "chartsheet chart ownership")
    chart = cs._charts[0]
    plots = getattr(chart, "_charts", [])
    require([type(p).__name__ for p in plots] == ["BarChart", "LineChart"], "combo plot families")
    require(list(plots[0].axId) == [10, 100], "primary chart axes")
    require(list(plots[1].axId) == [10, 200], "secondary chart axes")


def check_pivot(path: Path) -> None:
    wb = load_workbook(path, data_only=False)
    count = sum(len(getattr(ws, "_pivots", [])) for ws in wb.worksheets)
    require(count == 1, "PivotTable discovery")


def check_preserved_chartsheet(path: Path) -> None:
    wb = load_workbook(path, data_only=False)
    require(wb.sheetnames == ["Data", "Chart View"], "preserved chartsheet tab order")
    require(len(wb.chartsheets) == 1 and len(wb.chartsheets[0]._charts) == 1,
            "preserved imported chartsheet ownership")


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print(__doc__.strip(), file=sys.stderr)
        return 2
    check_chartsheet(Path(sys.argv[1]))
    check_pivot(Path(sys.argv[2]))
    if len(sys.argv) == 4:
        check_preserved_chartsheet(Path(sys.argv[3]))
    import openpyxl
    print(f"P1T openpyxl host check: PASS (openpyxl {openpyxl.__version__})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
